### ISSUE TITLE
Old todo list, to assess and maybe split

### ISSUE THREAD

**Issue by akien-mga** [godotengine/collada-exporter#1]
Taken from https://github.com/godotengine/collada-exporter/blob/9e89ca5/io_scene_dae/export_dae.py#L30-L39

### TODO:

- [ ] Materials & Textures
- [ ] Optionally export Vertex Colors
- [ ] Morph Targets
- [ ] Control bone removal
- [ ] Copy textures
- [ ] Export Keyframe Optimization
- [ ] Blender native material? (?)

**Comment by paper-pauper** [comment]
It would be useful to have a comment on each of those from the author to understand them better. @reduz was it you?

**Comment by paper-pauper** [comment]
@akien-mga Task 5 was closed in #2, please acknowledge.
